### PR TITLE
Add minio upload provider

### PR DESCRIPTION
**Pull request by krisis**
[minio](https://github.com/minio/minio/) upload provider will allow users to upload Travis-CI artifacts onto
their self-hosted Minio object storage server.

### CODE REVIEW

**Comment by bigbes** [comment]
Great feature! Would love to use it in conjuction with Travis.

**Comment by krisis** [comment]
@BanzaiMan @meatballhat Did you get a chance to look at the change?

**Comment by krisis** [comment]
@meatballhat @BanzaiMan Is it likely to get reviewed in the near future? I can understand if you are busy.

**Comment by krisis** [comment]
Closing this PR. Feel free to reopen if anyone finds this useful.

**Comment by OmgImAlexis** [comment]
Is there any chance is this being reopened any time soon?

**Comment by atomlab** [comment]
I agree this feature really needed

**Pull request closed without merging**
